openapi: 3.0.3
info:
    title: Ledger API
    description: Record cash inflow and outflow
    version: "1.0"
servers:
    - url: http://localhost:8080
paths:
    /openapi.json:
        get:
            tags:
                - ledger
            summary: Download ./gen/http/openapi.json
            operationId: ledger#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /user/{userID}/expenses:
        post:
            tags:
                - ledger
            summary: RecordExpense ledger
            operationId: ledger#RecordExpense
            parameters:
                - name: userID
                  in: path
                  description: user id
                  required: true
                  schema:
                    type: integer
                    description: user id
                    example: 627136460708173706
                    format: int64
                  example: 2019527979905914026
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                amount:
                                    type: number
                                    description: amount spent
                                    example: 0.23741224963273735
                                    format: double
                                category:
                                    type: string
                                    description: category
                                    example: Aliquid omnis voluptatem ea et.
                                memo:
                                    type: string
                                    description: memo
                                    example: Minima pariatur perferendis est beatae error.
                            example:
                                amount: 0.6329974919889713
                                category: Distinctio id aut.
                                memo: Quibusdam exercitationem blanditiis quis et et dolores.
                        example:
                            amount: 0.784920288450885
                            category: Ut facilis officia amet dolores ad hic.
                            memo: Voluptatem qui velit libero enim nulla.
            responses:
                "201":
                    description: Created response.
                "400":
                    description: Bad Request response.
components: {}
tags:
    - name: ledger
      description: Record cash inflow and outflow
